server:
  address: 0.0.0.0
  port: 8080
  idleTimeout: 5s
kubernetes:
  enabled: true
consul:
  enabled: false
  address: 127.0.0.1:8500
  scheme: http
  caFile: ""
  certFile: ""
  keyFile: ""
  insecureSkipVerify: false
  token: ""
  timeout: 2s
concurrency: 5
httpHealthCheck:
  - timeout: 2s
    type: http
    host: 127.0.0.1
    port: 8500
    service: "test"
    namespace: "test_namespace"
    insecureSkipVerify: false
    requestPath: /test
  - type: https
    host: google.com
