name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize, labeled]


concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.20

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make test

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    services:
      consul:
        image: consul:latest
        ports:
          - 8500:8500
    steps:
      - uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - name: Add Consul test service
        run: curl --request PUT --data @test/testdata/consul_test_service.json http://127.0.0.1:8500/v1/catalog/register

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make integration-test