name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  GO_VERSION: 1.20.3

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  build:
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Generate changelog
        run: |
          brew tap git-chglog/git-chglog
          brew install git-chglog

          git-chglog --output /home/runner/release_changelog.md --template .chglog/RELEASE_CHANGELOG.tpl.md ${VERSION}
          cat /home/runner/release_changelog.md

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --release-notes=/home/runner/release_changelog.md --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}